# Generated by Django 4.0.5 on 2022-07-28 16:35

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meetup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='название митапа')),
                ('date', models.DateField(unique=True, verbose_name='дата проведения')),
            ],
            options={
                'verbose_name': 'митап',
                'verbose_name_plural': 'митапы',
            },
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'пользователь', 'verbose_name_plural': 'пользователи'},
        ),
        migrations.RemoveField(
            model_name='user',
            name='telegram_token',
        ),
        migrations.AddField(
            model_name='user',
            name='company_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='название компании'),
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='электронная почта'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_speaker',
            field=models.BooleanField(db_index=True, default=False, verbose_name='является докладчиком'),
        ),
        migrations.AddField(
            model_name='user',
            name='job_title',
            field=models.CharField(blank=True, max_length=50, verbose_name='название компании'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='фамилия'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, verbose_name='номер телефона'),
        ),
        migrations.AddField(
            model_name='user',
            name='questionnaire_filled',
            field=models.BooleanField(db_index=True, default=False, verbose_name='анкета заполнена'),
        ),
        migrations.AddField(
            model_name='user',
            name='telegram_id',
            field=models.IntegerField(default=123, unique=True, verbose_name='Идентификатор пользователя в Телеграмме'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='имя'),
        ),
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='название потока')),
                ('meetup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='streams', to='bot.meetup', verbose_name='поток')),
            ],
            options={
                'verbose_name': 'поток',
                'verbose_name_plural': 'потоки',
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='название доклада')),
                ('starts_at', models.TimeField(verbose_name='время начала')),
                ('ends_at', models.TimeField(verbose_name='время окончания')),
                ('speaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='bot.user', verbose_name='докладчик')),
                ('stream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='bot.stream', verbose_name='доклад')),
            ],
            options={
                'verbose_name': 'доклад',
                'verbose_name_plural': 'доклады',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='текст вопроса')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asked_questions', to='bot.user', verbose_name='автор вопроса')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_questions', to='bot.user', verbose_name='адресат вопроса')),
            ],
            options={
                'verbose_name': 'вопрос',
                'verbose_name_plural': 'вопросы',
            },
        ),
        migrations.AddField(
            model_name='meetup',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='meetups', to='bot.user', verbose_name='участники'),
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sum', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='сумма доната')),
                ('donated_at', models.DateTimeField(auto_now_add=True, verbose_name='дата и время доната')),
                ('donated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='bot.user', verbose_name='от кого донат')),
            ],
            options={
                'verbose_name': 'донат',
                'verbose_name_plural': 'донаты',
            },
        ),
    ]
