# Generated by Django 4.0.5 on 2022-07-28 13:16

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_meetup_alter_user_options_remove_user_telegram_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='номер телефона'),
        ),
    ]
