# Generated by Django 4.0.5 on 2022-07-29 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_meetup_status_alter_user_job_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='starts_at',
            field=models.TimeField(default='10:00:00', verbose_name='время начала'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='meetup',
            name='status',
            field=models.CharField(choices=[('OP', 'Открыт'), ('FN', 'Закрыт')], max_length=2, verbose_name='Статус мероприятия'),
        ),
    ]
