# Generated by Django 4.0.5 on 2022-07-30 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0006_alter_block_ends_at_alter_block_starts_at'),
        ('bot', '0006_block_starts_at_alter_meetup_status'),
    ]

    operations = [
    ]
