# Generated by Django 4.0.5 on 2022-08-01 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0008_alter_user_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='chat_id',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='ID номер чата телеграмм'),
        ),
    ]
