# Generated by Django 4.0.5 on 2022-08-02 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0009_user_chat_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='moderator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderating_blocks', to='bot.user', verbose_name='модератор'),
        ),
    ]
