# Generated by Django 3.2.15 on 2022-08-07 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0010_alter_block_moderator'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Question',
        ),
    ]
